[package]
name = "comet-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
comet-proto.workspace = true
comet-doc.workspace = true
comet-identity.workspace = true
comet-rpc.workspace = true
tokio.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true

[dev-dependencies]
async-trait.workspace = true
chrono.workspace = true
tempfile.workspace = true
