[package]
name = "comet-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rusqlite.workspace = true
thiserror.workspace = true

[dev-dependencies]
comet-doc.workspace = true
loro.workspace = true
serde_json.workspace = true
tempfile.workspace = true
